title: Py-IQCC
# tagline: C. Alcaide
description: Pàgina web del projecte Py-IQCC
author: Carles Alcaide
# baseurl: '/just-the-class' # the subpath of your site, e.g. /blog
url: 'https://calcide.github.io' # the base hostname & protocol for your site, e.g. http://example.com
# exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

logo: "/assets/images/iqcc2.png"
favicon_ico: "/assets/images/iqcc.jpeg"

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
# aux_links:
#   Kevin Lin:
#     - 'https://kevinl.info'
#   Just the Class on GitHub:
#     - 'https://github.com/kevinlin1/just-the-class'
# footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  
  
# For copy button on code
enable_copy_code_button: false

# To disable support for mermaid diagrams (https://mermaid-js.github.io/mermaid/),
# comment out the `mermaid` and `version` keys below
# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code

# Enable or disable heading anchors
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Inici de la pàgina"

footer_content: "Copyright &copy; 2022-2023 Carles Alcaide. Distribuit per una <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">llicència MIT.</a>"

plugins:
  - jekyll-seo-tag

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: A tenir en compte
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Perill
    color: red

kramdown:
  math_engine: katex
